config/routes.rb
Rails.application.routes.draw do
  root "main#index"

  get '/login' => 'session#new'
  get '/signup' => 'providers#new'
  post '/signup' => 'providers#create'
  post '/session' => 'session#create'
  delete '/session' => 'session#destroy'

  resources :providers
  resources :consumers

  namespace :api, defaults: { format: :json } do
    resources :boards, except: [:new, :edit]
    resources :lists, only: [:create, :update, :destroy]
    resources :cards, only: [:create, :show, :update, :destroy]
    resources :likes, only: [:create, :destroy]
  end
end

app/models/board.rb
class Board < ActiveRecord::Base
  has_many :lists, dependent: :destroy
  has_many :shared_boards, dependent: :destroy
  has_many :viewers, through: :shared_boards, source: :consumer
  belongs_to :provider


  def is_shared?(consumer)
    true if consumer.id == self.consumer_id
    shared_boards.where(consumer_id: consumer.id).exists?
  end
end

app/models/card.rb
class Card < ActiveRecord::Base
  belongs_to :list
  has_many :likes, dependent: :destroy
  has_many :issues, dependent: :destroy

  default_scope { order(:order) }
end

app/models/consumer.rb
class Consumer < ActiveRecord::Base

  validates_uniqueness_of :email
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create

  belongs_to :provider
  has_many :issues
  has_many :likes
  has_many :shared_boards

  has_secure_password

end

app/models/issue.rb
class Issue < ActiveRecord::Base
  belongs_to :list
  belongs_to :card
  belongs_to :consumer
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :card
  belongs_to :consumer
end

app/models/list.rb
class List < ActiveRecord::Base
  belongs_to :board
  has_many :cards, dependent: :destroy
  default_scope { order(:order) }
end

app/models/provider.rb
class Provider < ActiveRecord::Base
  validates_uniqueness_of :email
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create

  has_many :consumers
  has_many :boards

  has_secure_password
end

app/models/shared_board.rb
class SharedBoard < ActiveRecord::Base
  belongs_to :consumer
  belongs_to :board
end

app/controllers/api/api_controller.rb
module Api
  class ApiController < ApplicationController
  end
end

app/controllers/api/cards_controller.rb
module Api
  class CardsController < ApiController


    def create
      @card = current_list.cards.new(card_params)

      if @card.save
        render json: @card
      else
        render json: @card.errors.full_messages, status: :unprocessable_entity
      end
    end

    def update
      @card = Card.find(params[:id])
      if @card.update_attributes(card_params)
        render json: @card
      else
        render json: @card.errors.full_messages,
               status: :unprocessable_entity
      end
    end

    def show
      @card = Card.find(params[:id])
      render :show
    end

    private

    def current_list
      if params[:id]
        @card = Card.find(params[:id])
        @list = @card.list
      elsif params[:card]
        @list = List.find(params[:card][:list_id])
      end
    end

    def current_board
      current_list.board
    end

    def card_params
      params.require(:card).permit(:title, :list_id, :order, :description)
    end
  end
end

app/controllers/api/items_controller.rb
module Api
  class LikesController < ApiController
    def create
      @likes = Like.new(like_params)

      if @likes.save
        render json: @likes
      else
        render json: @likes.errors.full_messages, status: :unprocessable_entity
      end
    end

    def destroy
      @like = Like.find(params[:id])
      @like.destroy
      render json: { message: 'destroyed!' }
    end

    private

    def like_params
      params.require(:like).permit(:done, :card_id, :consumer_id)
    end
  end
end

app/controllers/api/lists_controller.rb
module Api
  class ListsController < ApiController

    def create
      @list = current_board.lists.new(list_params)

      if @list.save
        render json: @list
      else
        render json: @list.errors.full_messages, status: :unprocessable_entity
      end
    end

    def destroy
      @list = List.find(params[:id])
      @list.destroy
      render json: {}
    end

    def update
      @list = current_board.lists.find(params[:id])

      if @list.update_attributes(list_params)
        render json: @list
      else
        render json: @list.errors.full_messages, status: :unprocessable_entity
      end
    end

    private

    def current_board
      if params[:id]
        @list = List.find(params[:id])
        @board = @list.board
      elsif params[:list]
        @board = Board.find(params[:list][:board_id])
      end
    end

    def list_params
      params.require(:list).permit(:title, :board_id, :order)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  
end

app/controllers/consumers_controller.rb
class ConsumersController < ApplicationController
  respond_to :html, :json

  def new
    @consumer = Consumer.new
  end

  def create
    if params[:password] == params[:confirm_password]
      @consumer = Consumer.create(params_consumer)
      redirect_to @consumer

    else
      redirect_to '/consumers/new'
    end
  end

  def index
    @consumers = Consumer.all
  end

  def edit
    @consumer = Consumer.find_by(id: params[:id])

    if session[:provider_id] == @consumer.provider_id
    else
      redirect_to '/'
    end

  end

  def update
    @consumer = Consumer.find_by(id: params[:id])
    if @consumer.update_attributes(params_consumer)
      respond_to do |format|
        format.html { redirect_to :back}
        format.json { respond_with_bip(@consumer) }
      end
    else
      render :show
    end
  end

  def show
    @consumer = Consumer.find_by(id: params[:id])
  end

  

  def destroy
    @consumer = Consumer.find_by(id: params[:id])

    Consumer.destroy(params[:id])


    redirect_to provider_path
  end

  def params_consumer
    params.require(:consumer).permit(:name, :password, :email, :provider_id, :birthday, :gender)
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController

  def index
    session[:page_id] = '/'
  end

end

app/controllers/providers_controller.rb
class ProvidersController < ApplicationController
  def new
    @provider = Provider.new
  end

  def create
    if params[:password] == params[:confirm_password]
      @provider = Provider.create(params_provider)
      redirect_to '/providers'

    else
      redirect_to '/signup'
    end
  end

  def index
    @providers = Provider.all
  end



  def show
    @provider = Provider.find_by(id: params[:id])
    @consumers = Consumer.where(provider_id: params[:id])
    @boards = Board.where(provider_id: params[:id])
    @cards = Card.where(provider_id: params[:id])
  end



  def params_provider
    params.require(:provider).permit(:name, :password, :email)
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
    render :new
  end

  def create
    provider = Provider.find_by(email: params[:email])
    consumer = Consumer.find_by(email: params[:email])
    if provider && provider.authenticate(params[:password])
      session[:provider_id] = provider.id
      redirect_to provider
    elsif consumer && consumer.authenticate(params[:password])
      session[:consumer_id] = consumer.id
      redirect_to consumer
    else
      render :new
    end
  end

  def destroy
    reset_session
    redirect_to :back
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/board_helper.rb
module BoardHelper
end

app/helpers/card_helper.rb
module CardHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/views/card/create.html.erb
<h1>Card#create</h1>
<p>Find me in app/views/card/create.html.erb</p>

app/views/card/destroy.html.erb
<h1>Card#destroy</h1>
<p>Find me in app/views/card/destroy.html.erb</p>

app/views/card/edit.html.erb
<h1>Card#edit</h1>
<p>Find me in app/views/card/edit.html.erb</p>

app/views/card/index.html.erb
<h1>Card#index</h1>
<p>Find me in app/views/card/index.html.erb</p>

app/views/card/new.html.erb
<h1>Card#new</h1>
<p>Find me in app/views/card/new.html.erb</p>

app/views/card/show.html.erb
<h1>Card#show</h1>
<p>Find me in app/views/card/show.html.erb</p>

app/views/card/update.html.erb
<h1>Card#update</h1>
<p>Find me in app/views/card/update.html.erb</p>

app/views/providers/dash.html.erb
Welcome <%= provider.name  %>

These are your consumers

<ul>
<% @consumers.each do |consumer|   %>
<li><%= consumer.name %></li>
<% end  %>
</ul>

Add consumers here:

<input type="text" action="POST">

app/views/providers/edit.html.erb
	<h2><%= best_in_place @consumer, :name %></h2>
	<p><%= best_in_place @consumer, :email  %></p>
	
	<p><%= best_in_place @consumer, :birthday %></p>

app/views/providers/index.html.erb
These are the current providers
<ul>
<% @providers.each do |provider|   %>
<li><%= provider.name %></li>
<% end  %>
</ul>

app/views/providers/new.html.erb
	<%= form_for @provider, url: {action: 'create'}, :html => { :class => 'form-horizontal'} do |f| %>
	<fieldset>
  	<legend>Register for DrEllo</legend>
	<div class="control-group">
	<%= f.label :name, class: 'control-label' %>
	
	<div class="controls">
	<%= f.text_field :name %>
	</div>
	</div>

	<div class="control-group">
	<%= f.label :password, class: 'control-label' %>
	<div class="controls">
	<%= f.text_field :password %>
	</div>
	</div>
	
  	<div class="control-group">
  	<%= f.label :email, class: 'control-label' %>
  	<div class="controls">
  	<%= email_field(:provider, :email) %>
  	</div>
  	</div>
	
	<div class="control-group">
  	<%= f.label :trello_name, class: 'control-label' %>
  	<div class="controls">
  	<%= f.text_field(:trelloName) %>
  	</div>
  	</div>
	
	<% f.hidden_field :authenticity_token, value: form_authenticity_token() %> 
	

	<div class="form-actions">
	<br>
	<%= f.submit 'Sign Up', class: 'btn btn-default btn-xs' %>
	</div>
<% end %>

app/views/providers/show.html.erb
Welcome <%= @provider.name  %>
<br>
Here's your current caseload:

<ul>
<% @consumers.each do |consumer|   %>
<!-- Dropdown Trigger -->
  <a class='dropdown-button btn blue' href='#' data-activates='dropdown<%=consumer.id%>'><%= consumer.name  %></a>
  <!-- Dropdown Structure -->
  <ul id='dropdown<%=consumer.id%>' class='dropdown-content'>
    <li><%= link_to 'Show', consumer_path(consumer) %></li>
    <li class="divider"></li>
    <li><%= link_to 'Edit', edit_consumer_path(consumer) %></li>
    <li class="divider"></li>
    <li><%= link_to 'Delete', consumer_path(consumer), method: :delete %></li>
  </ul>
  <br>
<% end  %>
</ul>




<div class="droppable row"><div class="col s6 m4"><div class="card blue-grey darken-1"><div class="card-content white-text"><span class="card-title">List</span><div class="row"><div class="col s1 m12"><div class="draggable card-panel white"><span class="grey-text">Draggable card</span><div class="card-action"><a href="#">Helpful</a></div></div></div></div></div></div></div></div>


<div class='draggable'></div>
<input type='button' class='content' value='Create card'/>
<div class='lists'></div>

<div class="backdrop">
  <div id="main"></div>
</div>
<script>$(Drello.initialize);</script>
<script>
$(document).ready(function(){
    $('.dropdown-button').dropdown({
    inDuration: 300,
    outDuration: 225,
    constrain_width: true, // Does not change width of dropdown to that of the activator
    hover: false, // Activate on click
    alignment: 'left', // Aligns dropdown to left or right edge (works with constrain_width)
    gutter: 0, // Spacing from edge
    belowOrigin: true // Displays dropdown below the button
    }
);


    


    $( ".draggable" ).draggable({
    	revert: "invalid", snap: "true", snapMode: "inner" 
    });
    $(".droppable").droppable({
    drop: function( event, ui ) {
           ui.helper.css('top','');
           ui.helper.css('left','');

        }
   });
    $('.content').click(function(){
        var htmlData='<div class="row"><div class="col s6 m4"><div class="droppable card blue-grey darken-1"><div class="card-content white-text"><span class="card-title">draggable list</span><div class="row"><div class="col s1 m12"><div class="draggable card-panel white"><span class="grey-text">Card Title</span><div class="card-action"><a href="#">Helpful</a></div></div></div></div></div></div></div></div>';
        $('.lists').append(htmlData);
        $( ".draggable" ).draggable();
        });
    
});
</script>